"""add new columns

Revision ID: 40aa61d9e21a
Revises: 40ab47a45c7e
Create Date: 2026-02-17 15:15:48.372374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40aa61d9e21a'
down_revision: Union[str, Sequence[str], None] = '40ab47a45c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoint', sa.Column('path', sa.String(), nullable=False))
    op.add_column('endpoint', sa.Column('method', sa.String(), nullable=False))
    op.drop_column('endpoint', 'name')
    op.add_column('group', sa.Column('endpoint', sa.String(), nullable=False))
    op.add_column('group', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('group', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'description')
    op.drop_column('group', 'active')
    op.drop_column('group', 'endpoint')
    op.add_column('endpoint', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('endpoint', 'method')
    op.drop_column('endpoint', 'path')
    # ### end Alembic commands ###
