"""add goup_id to endpoint table

Revision ID: 40ab47a45c7e
Revises: 165622059173
Create Date: 2026-02-17 15:01:37.473513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40ab47a45c7e'
down_revision: Union[str, Sequence[str], None] = '165622059173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoint', sa.Column('group_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('endpoint_user_id_fkey'), 'endpoint', type_='foreignkey')
    op.create_foreign_key(None, 'endpoint', 'group', ['group_id'], ['id'])
    op.drop_column('endpoint', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoint', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'endpoint', type_='foreignkey')
    op.create_foreign_key(op.f('endpoint_user_id_fkey'), 'endpoint', 'user', ['user_id'], ['id'])
    op.drop_column('endpoint', 'group_id')
    # ### end Alembic commands ###
